[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.6"
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tower-http = { version = "0.4", features = ["cors"] }

# PostgreSQL dependencies
tokio-postgres = "0.7"
tokio-native-tls = "0.3"
dotenv = "0.15"


# Reqwest for HTTP requests
reqwest = { version = "0.11", features = ["json"] }